"""First migration

Revision ID: 8179b6014890
Revises: 
Create Date: 2023-05-26 12:50:36.297671

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8179b6014890'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('location',
    sa.Column('zip', sa.String(length=5), nullable=False),
    sa.Column('state_name', sa.String(length=256), nullable=False),
    sa.Column('city', sa.String(length=256), nullable=False),
    sa.Column('lat', sa.String(length=10), nullable=False),
    sa.Column('lng', sa.String(length=10), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_location'))
    )
    with op.batch_alter_table('location', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_location_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_location_zip'), ['zip'], unique=True)

    op.create_table('car',
    sa.Column('number', sa.String(length=5), nullable=False),
    sa.Column('current_location', sa.Integer(), nullable=True),
    sa.Column('weight', sa.Integer(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['current_location'], ['location.id'], name=op.f('fk_car_current_location_location')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_car'))
    )
    with op.batch_alter_table('car', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_car_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_car_number'), ['number'], unique=True)

    op.create_table('cargo',
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('delivery_location', sa.Integer(), nullable=True),
    sa.Column('current_location', sa.Integer(), nullable=True),
    sa.Column('weight', sa.Integer(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['current_location'], ['location.id'], name=op.f('fk_cargo_current_location_location')),
    sa.ForeignKeyConstraint(['delivery_location'], ['location.id'], name=op.f('fk_cargo_delivery_location_location')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_cargo'))
    )
    with op.batch_alter_table('cargo', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_cargo_id'), ['id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('cargo', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_cargo_id'))

    op.drop_table('cargo')
    with op.batch_alter_table('car', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_car_number'))
        batch_op.drop_index(batch_op.f('ix_car_id'))

    op.drop_table('car')
    with op.batch_alter_table('location', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_location_zip'))
        batch_op.drop_index(batch_op.f('ix_location_id'))

    op.drop_table('location')
    # ### end Alembic commands ###
