"""First migration

Revision ID: c39bff01622c
Revises: 
Create Date: 2023-05-24 18:12:31.003500

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c39bff01622c'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('location',
    sa.Column('zip', sa.String(length=100), nullable=False),
    sa.Column('state', sa.String(length=256), nullable=False),
    sa.Column('city', sa.String(length=256), nullable=False),
    sa.Column('lat', sa.String(length=100), nullable=False),
    sa.Column('lng', sa.String(length=100), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_location')),
    sa.UniqueConstraint('zip', name=op.f('uq_location_zip'))
    )
    op.create_table('car',
    sa.Column('item_id', sa.String(length=5), nullable=False),
    sa.Column('current_location', sa.Integer(), nullable=True),
    sa.Column('weight', sa.Integer(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['current_location'], ['location.id'], name=op.f('fk_car_current_location_location')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_car')),
    sa.UniqueConstraint('item_id', name=op.f('uq_car_item_id'))
    )
    op.create_table('cargo',
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('delivery_location', sa.Integer(), nullable=True),
    sa.Column('item_id', sa.String(length=5), nullable=False),
    sa.Column('current_location', sa.Integer(), nullable=True),
    sa.Column('weight', sa.Integer(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['current_location'], ['location.id'], name=op.f('fk_cargo_current_location_location')),
    sa.ForeignKeyConstraint(['delivery_location'], ['location.id'], name=op.f('fk_cargo_delivery_location_location')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_cargo')),
    sa.UniqueConstraint('item_id', name=op.f('uq_cargo_item_id'))
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('cargo')
    op.drop_table('car')
    op.drop_table('location')
    # ### end Alembic commands ###
